<?php

/**
* Router.php
*
* Determines which code to run for a particular request.
*
* @author Greg
*/

class Router {
	private $html_output;

	public function __construct() {
		$this->html_output = '';
	}

	public function __destruct() {}

	public function route() {
		$output = '';
		$route_name = $this->setRouteName();
		$output = $this->selectController($route_name);

		$this->html_output = $output;

	}

	public function setRouteName(): string {
		if (isset($_POST['route'])) {
			$route = $_POST['route'];
		} else if (isset($_GET['route'])) {
			$route = $_GET['route'];
		} else  {
			$route = 'index';
		}

		return $route;
	}

	/**
	* Calls an appropriate controller for a particular request.
	* 
	* @param route - value sent after submitting an HTML form.
	*
	* @return - html output generated by controller.
	*/
	public function selectController(string $route): string {
		switch ($route) {
			case 'information':
				$controller = Creator::createObject('IndexController');
				$controller->set('information');
				break;
			case 'terms':
				$controller = Creator::createObject('IndexController');
				$controller->set('terms');
				break;
			case 'user_login':
				$controller = Creator::createObject('IndexController');
				$controller->set('login');
				break;
			case 'process_login':
				$controller = Creator::createObject('LoginController');
				break;
			case 'user_logout':
				$controller = Creator::createObject('LogoutController');
				break;
			case 'student_main':
				$controller = Creator::createObject('StudentController');
				$controller->set('home');
				break;
			case 'teacher_main':
				$controller = Creator::CreateObject('TeacherController');
				$controller->set('home');
				break;
			case 'edit_student':
				$controller = Creator::createObject('StudentController');
				$controller->set('edit');
				break;
			case 'edit_teacher':
				$controller = Creator::createObject('TeacherController');
				$controller->set('edit');
				break;
			case 'edit_student_password':
				$controller = Creator::createObject('StudentController');
				$controller->set('edit_password');
				break;
			case 'edit_password':
				$controller = Creator::createObject('UserController');
				$controller->set('edit_password');
				break;
			case 'support_student':
				$controller = Creator::createObject('StudentController');
				$controller->set('support');
				break;
			case 'edit_user':
				$controller = Creator::createObject('UserController');
				$controller->set('edit_user');
				break;
			case 'student_documents':
				$controller = Creator::createObject('StudentController');
				$controller->set('view_documents');
				break;
			case 'student_view_grades':
				$controller = Creator::createObject('StudentController');
				$controller->set('view_grades');
				break;
			case 'see_grades':
				$controller = Creator::createObject('StudentController');
				$controller->set('show_grades');
				break;
			case 'teacher_support':
				$controller = Creator::createObject('TeacherController');
				$controller->set('support');
				break;
			case 'edit_teacher_password':
				$controller = Creator::createObject('TeacherController');
				$controller->set('edit_password');
				break;
			case 'teacher_groups':
				$controller = Creator::createObject('TeacherController');
				$controller->set('groups');
				break;
			case 'view_assessments':
				$controller = Creator::createObject('TeacherController');
				$controller->set('assessments');
				break;
			case 'add_assessment':
				$controller = Creator::createObject('AssessmentController');
				$controller->set('add_assessment');
				break;
			case 'add_assessment':
				$controller = Creator::createObject('AssessmentController');
				$controller->set('edit_assessment');
				break;
			case 'view_group':
				$controller = Creator::createObject('TeacherController');
				$controller->set('view_group');
				break;
			case 'drop_assessment':
				$controller = Creator::createObject('AssessmentController');
				$controller->set('drop_assessment');
				break;
			case 'student_view_assessments':
				$controller = Creator::CreateObject('StudentController');
				$controller->set('view_assessments');
				break;
			case 'see_assessments':
				$controller = Creator::CreateObject('StudentController');
				$controller->set('view_upcoming');
				break;
			case 'teacher_edit_assessment':
				$controller = Creator::createObject('TeacherController');
				$controller->set('edit_assessment');
				break;
			case 'edit_assessment':
				$controller = Creator::createObject('AssessmentController');
				$controller->set('edit_assessment');
				break;
			default:
				$controller = Creator::createObject('IndexController');
				$controller->set('main');
		}

		$controller->createHtmlOutput();
		$output = $controller->getHtmlOutput();
		return $output;
	}

	public function getHtmlOutput() {
		return $this->html_output;
	}
}